### ISSUE TITLE
Drop plone.recipe.precompiler?

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/ftw-buildouts#41]
If used with a combined policy / buildout where the policy is checked out from source, and used with `develop = .`, the use of `plone.recipe.precompiler` will cause the entire deployment directory being scanned during buildout, including directories like `var/`.

If `var/` contains a `blobstorage` with a ton of files, this will slow down buildout to the point where it basically won't finish.

So, can we drop `plone.recipe.precompiler` from `production.cfg`? I don't quite see the point of it anyway: One reason for its existence it is to avoid writes during application lifetime to code directories, but this point is void anyway if we're keeping `var/` inside a Python development egg.

@jone @maethu @buchi can we remove this? Or what was the original motivation for including it?

**Comment by jone** [comment]
> One reason for its existence it is to avoid writes during application lifetime to code directories, but this point is void anyway if we're keeping var/ inside a Python development egg.
I think the goal is to not write to the (shared?) egg cache.

I think we've started using it because we actually had no / wrong / not updated translations in some situations, which is quite bad, also because we wouldn't notice.

I have no problem with stop using it / removing from `production.cfg` if we are sure that the user still has always the current translations.

**Comment by lukasgraf** [comment]
@jone 
I'm guessing that `zope_i18n_compile_mo_files true` for the Zope-Instance wasn't set then:
http://vincentfretin.ecreall.com/articles/my-translation-doesnt-show-up-in-plone-4

We've [got that in `production.cfg` now](https://github.com/4teamwork/ftw-buildouts/blob/0ae1cdabc79027772d6b049b08bc7c845728c866/production.cfg#L90) though.

**Comment by jone** [comment]
Yes, probably.
@maethu any objections?

**Comment by maethu** [comment]
Go ahead, gonna put it back if necessary 😜
